### ISSUE TITLE
ImportError: No module named enum

### ISSUE THREAD

**Issue by djcf** [MichaelLindsey/alp-deluge#1]
Excellent work! However, I encounter the following permanent error:

root@daedalus ~/docker-images# docker run -d --name=alp-deluge -v /mnt/data:/torrents -p 8112:8112 alpinedeluge
db7e6cfe5441a2b6491776ee7c2166444c61798c5247acf9f573f782e9c2f767
root@daedalus ~/docker-images# docker logs alp-deluge
[ERROR   ] 19:43:50 main:237 No module named enum
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/deluge/main.py", line 229, in start_daemon
    from deluge.core.daemon import Daemon
  File "/usr/lib/python2.7/site-packages/deluge/core/daemon.py", line 45, in <module>
    from deluge.core.rpcserver import RPCServer, export
  File "/usr/lib/python2.7/site-packages/deluge/core/rpcserver.py", line 45, in <module>
    from twisted.internet import ssl, reactor, defer
  File "/usr/lib/python2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
    from cryptography.exceptions import InternalError
  File "/usr/lib/python2.7/site-packages/cryptography/exceptions.py", line 7, in <module>
    from enum import Enum
ImportError: No module named enum
Traceback (most recent call last):
  File "/usr/bin/deluge-web", line 9, in <module>
    load_entry_point('deluge==1.3.11', 'console_scripts', 'deluge-web')()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 138, in start
    web.start()
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/web.py", line 107, in start
    import server
  File "/usr/lib/python2.7/site-packages/deluge/ui/web/server.py", line 51, in <module>
    from twisted.internet.ssl import SSL
  File "/usr/lib/python2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
    from cryptography.exceptions import InternalError
  File "/usr/lib/python2.7/site-packages/cryptography/exceptions.py", line 7, in <module>
    from enum import Enum
ImportError: No module named enum

Any ideas?

**Comment by MichaelLindsey** [comment]
Hi djcf, there was a missing python module perhaps a recent update to deluge. I've updated to the Dockerfile and can confirm working build from scratch. Updated the readme for better clarity, let us know if issues persist.
